### ISSUE TITLE
Unable to translate "Auto (default on light theme, darcula on dark theme)"

### ISSUE THREAD

**Issue by rob006** [clarkwinkelmann/flarum-ext-scratchpad#1]
This string is hardcoded:

https://github.com/clarkwinkelmann/flarum-ext-scratchpad/blob/53d3d4f4f33c703b726a13f67d28f1f9e7e3cd9a/js/src/admin/components/CodeMirrorSettingsModal.js#L84

**Comment by clarkwinkelmann** [comment]
Thanks for the report! Fixed in version 1.1.0. There are also 3 new other translations due to the added features :)
